[package]
name = "message-during-pending"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { git = "https://github.com/WorldSEnder/yew.git", rev = "3cf0e6e", features = ["csr"] }
